---
- hosts: webserver
  become: yes

  tasks:

    - name: Update the apt-get of the ec2 instance
      apt:
        update_cache: yes

    - name: Install apache2
      apt:
        name: apache2
        state: present
    
    - name: Install Python
      apt:
        name: python3
        state: latest

    - name: Install pip
      apt:
        name: python3-pip
        state: latest
    
    - name: Install Paramiko library
      command: "pip install paramiko"

    - name: Install SCP library
      command: "pip install scp"

    - name: Copy the SSH file to the webserver
      copy:
        mode: 0400
        src: "{{ ssh_local }}"
        dest: "{{ ssh_remote }}"

   
    - name: Copy the Python script
      copy:
        mode: 0606
        src: "{{ app_directory_local }}"
        dest: "{{ app_directory_remote }}"

    - name: Copy the website
      copy:
        mode: 0606
        src: "{{ web_directory_local }}"
        dest: "{{ web_directory_remote }}"

    - name: install flask with pip
      pip: name=flask
    - name: Start Flask webserver
      command: "python3 /home/ubuntu/website/main.py"
